[warmup_1]
input_datasets = ["seviri"]
reference_datasets = ["baltrad"]
training_data_path = "ENV::{TMPDIR}/training_data"
validation_data_path = "ENV::{TMPDIR}/validation_data"
optimizer = "AdamW"
batch_size = 1
optimizer_args = {"lr"=1e-3}
scheduler = "Warmup"
sequence_length = 16
n_epochs = 20
sample_rate = 0.25
scene_size = 256
require_input = true
accumulate_grad_batches = 4
n_data_loader_workers = 6
metrics = ["CorrelationCoef", "Bias", "MSE"]
load_weights = "efficient_net_2p1_pretrained.pt"

[stage_1]
input_datasets = ["seviri"]
reference_datasets = ["baltrad"]
training_data_path = "ENV::{TMPDIR}/training_data"
validation_data_path = "ENV::{TMPDIR}/validation_data"
optimizer = "AdamW"
scheduler = "CosineAnnealingLR"
scheduler_args = {T_max = 30}
batch_size = 1
optimizer_args = {"lr"=5e-4}
sequence_length = 16
n_epochs = 30
sample_rate = 4
scene_size = 256
require_input = true
accumulate_grad_batches = 4
n_data_loader_workers = 6
metrics = ["CorrelationCoef", "Bias", "MSE"]
reuse_optimizer = true

[warmup_2]
input_datasets = ["seviri"]
reference_datasets = ["baltrad"]
training_data_path = "ENV::{TMPDIR}/training_data"
validation_data_path = "ENV::{TMPDIR}/validation_data"
optimizer = "AdamW"
batch_size = 1
optimizer_args = {"lr"=5e-4}
scheduler = "Warmup"
sequence_length = 16
n_epochs = 20
sample_rate = 0.25
scene_size = 256
require_input = true
accumulate_grad_batches = 4
n_data_loader_workers = 6
metrics = ["CorrelationCoef", "Bias", "MSE"]
reuse_optimizer = true

[stage_2]
input_datasets = ["seviri"]
reference_datasets = ["baltrad"]
training_data_path = "ENV::{TMPDIR}/training_data"
validation_data_path = "ENV::{TMPDIR}/validation_data"
optimizer = "AdamW"
scheduler = "CosineAnnealingLR"
scheduler_args = {T_max = 50}
batch_size = 1
optimizer_args = {"lr"=5e-4}
sequence_length = 16
n_epochs = 50
sample_rate = 4
scene_size = 256
require_input = true
accumulate_grad_batches = 4
n_data_loader_workers = 6
metrics = ["CorrelationCoef", "Bias", "MSE"]
reuse_optimizer = true

[warmup_3]
input_datasets = ["seviri"]
reference_datasets = ["baltrad"]
training_data_path = "ENV::{TMPDIR}/training_data"
validation_data_path = "ENV::{TMPDIR}/validation_data"
optimizer = "AdamW"
scheduler = "Warmup"
batch_size = 2
optimizer_args = {"lr"=1e-4}
sequence_length = 16
n_epochs = 20
sample_rate = 0.25
scene_size = 256
require_input = true
accumulate_grad_batches = 4
n_data_loader_workers = 6
metrics = ["CorrelationCoef", "Bias", "MSE"]
reuse_optimizer = true

[stage_3]
input_datasets = ["seviri"]
reference_datasets = ["baltrad"]
training_data_path = "ENV::{TMPDIR}/training_data"
validation_data_path = "ENV::{TMPDIR}/validation_data"
optimizer = "AdamW"
scheduler = "CosineAnnealingLR"
scheduler_args = {T_max = 20}
batch_size = 2
optimizer_args = {"lr"=1e-4}
sequence_length = 16
n_epochs = 20
sample_rate = 4
scene_size = 256
require_input = true
accumulate_grad_batches = 4
n_data_loader_workers = 6
metrics = ["CorrelationCoef", "Bias", "MSE"]
reuse_optimizer = true
